### ISSUE TITLE
decide on a dataset to use

### ISSUE THREAD

**Issue by laurasootes** [esciencecenter-digital-skills/Natural-language-processing#3]
Decde which data set to use throughout the workshop

**Comment by laurasootes** [comment]
Decided on: 
[gutenberg corpus]( https://github.com/pgcorpus/gutenberg-analysis)

- Contains books with expired licenses
- publicly available
- appealing to audience

**Comment by n400peanuts** [comment]
We will focus on the Sherlock Holmes books

**Comment by laurasootes** [comment]
download from: https://www.gutenberg.org/ebooks/69700

**Comment by n400peanuts** [comment]
We have the dataset, we can close this issue
