### ISSUE TITLE
Define a storyline to use throughout the workshop

### ISSUE THREAD

**Issue by laurasootes** [esciencecenter-digital-skills/Natural-language-processing#4]
We will use the Gutenberg dataset (#3 ), which contains books. Decide how to use these book data and what interesting questions can be answered with this data

**Comment by laurasootes** [comment]
Idea:

1 identify names / places in text
2 character identification: what type of characters are they (hero, villain, etc.) bit of sentitiment analysis
3 classify characters in good/bad ?
4 relationships between characters?
5 select a bunch of common names and identifiy how the character evolves over time; for example is Eva a always a positive character 200 years ago, and is Eva now more often a negative character?

**Comment by n400peanuts** [comment]
6 - Degree of sociability: Measured as the number of instances in which a character appears in the same sentence as another character

7 - Communicativeness: Percentage of times that a character engages in some form of dialogue — with a list of verbs of communication:  https://www.proofreadingservices.com/pages/verbs-of-communication

**Comment by n400peanuts** [comment]
this issue is very old - we have moved to other approaches to shape the story for this course that this issue is not relevant anymore
