### ISSUE TITLE
Develop episode 1

### ISSUE THREAD

**Issue by laurasootes** [esciencecenter-digital-skills/Natural-language-processing#6]
In this task @n400peanuts  will develop the first episode. 

This is the tentative list of content for this episode:

Chapter title: What natural language processing is and why we care about it 

Learning goal of this chapter: (same as the title!) 

 

> What is NLP/why we care 
> 
> Tools/packages we are going to use  
> 
> Applications and tasks 
> 
> Structure and story of day 1 and day 2 (i.e., what dataset we are going to use, why, which problem, NER, we are going to focus on)

**Comment by n400peanuts** [comment]
- [ ] Define learning goals
- [ ] what is nlp
- [ ] justify why we care about nlp
- [ ] applications and tasks: categorising text, semantic search, text clustering and topic modelling, text generation 
- [ ] dataset / gutenberg
- [ ] structure of day 1-day 2
